export const PROCESSING_STATUS = {
  UNPROCESSED: 'UNPROCESSED',
  QUEUED: 'QUEUED',
  PROCESSING: 'PROCESSING',
  COMPLETE: 'COMPLETE',
  FAILED: 'FAILED',
  GRAPH_FAILED: 'GRAPH_FAILED'
} as const;
